/**
 * Health Alerts
 * This application allows users to send and receive information about a user's health condition.
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.server.resource;


import org.openapitools.server.R;
import org.openapitools.server.model.*;
import org.openapitools.server.response.*;

import java.util.*;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;


import org.openapitools.server.model.Event;



import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

import android.app.AlertDialog;
import android.content.Context;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.Volley;

import android.content.Intent;
import android.net.Uri;
import android.util.Log;
import android.widget.Toast;


public class EventResource {

    private Context context;
    private RequestQueue request;

    private EventResponse eventResponse;

    public EventResource(Context context) {
        this.context = context;
        request = Volley.newRequestQueue(context);

    }

  public void executeMethod(EventResponse response){

        eventResponse=response;

      switch (response.getMethod()){
          case "postEvent":
            postEvent(response.getParams().getevent());
            break;
      }


  }

  /**
  * Sends an event
  * Sends an event
   * @param event Information about the event
   * @return String
  */
  public String postEvent (Event event){

    //TODO: Alert

      // Toast for notification
      Toast toast = Toast.makeText(context, "Alert!: "+event.getTitle()+" - "+event.getDescription(), Toast.LENGTH_LONG);
      toast.show();

      try {
          Thread.sleep(3000);
      } catch (InterruptedException e) {
          e.printStackTrace();
      }

      // Creates an Intent that will load a map with a mocked location
      Double lat = event.getLocation().getLatitude();
      Double lon = event.getLocation().getLongitude();
      Uri gmmIntentUri = Uri.parse("geo:"+lat+","+lon+"?q="+lat+","+lon+"("+event.getTitle()+" - "+event.getDescription()+")");
      Intent mapIntent = new Intent(Intent.ACTION_VIEW, gmmIntentUri);
      mapIntent.setPackage("com.google.android.apps.maps");
      context.startActivity(mapIntent);

      return null;
  }


}
